
TMDB_API:
MOVIE_TEMPLATE: "\
{{target_path}}/\
{% if video_format == '2K' or video_format == '4K' %}Movies_HQ/\
{% elsif video_codec == 'HEVC'%}Movies_HEVC/\
{% else %}Movies/\
{%endif%}\
{{title}} ({{year}}){% if tag %} {{tags}}{% endif %}/\
{{title}} ({{year}}) {% if tag %}{{tags}} {% endif %}[{{video_format}}] \
{% if video_codec == 'HEVC' %}[HEVC] {%endif%}\
[{{audio_codec}}].{{ext}}"
TV_TEMPLATE: "{{target_path}}/TV/{{title}}/{{title}} S{{ tv_season | prepend: '0' | slice: -2, 2 }}/\
{{title}} S{{tv_season | prepend: '0' | slice: -2, 2 }}E{{tv_episode | prepend: '0' | slice: -2, 2 }} [{{video_format}}].{{ext}}"
