PLEX_TOKEN:
PLEX_PORT:
PLEX_HOST:  
MOVIE_TEMPLATE: "\
{{target_path}}/\
{% if video_format == '4K' %}Movies_HQ/{% else %}Movies/{%endif%}\
{{title}} ({{year}})/\
{{title}} ({{year}}) {% if tags %}[{{tags | join: ', ' }}] {% endif %}[{{video_format}}] \
{% if video_codec == 'HEVC' %}[HEVC] {% endif %}\
[{{audio_codec}}]\
{% if parts_count > 1 %} [Part {{part}}]{% endif %}\
.{{ext}}"
TV_TEMPLATE: "{{target_path}}/TV/{{title}}/{{title}} S{{ tv_season | prepend: '0' | slice: -2, 2 }}/\
{{title}} S{{tv_season | prepend: '0' | slice: -2, 2 }}E{{tv_episode | prepend: '0' | slice: -2, 2 }} \
[{{video_format}}]{% if parts_count > 1 %} [Part {{part}}]{% endif %}\
.{{ext}}"
